edited readme
whosFritz/Rail-Insights pull request #82
Opened 2024-03-05 13:14 UTC by whosFritz

2024-03-05 14:04 UTC, olech2412 requested changes

2024-03-05 14:04 UTC, olech2412 commented on README.md
>  Deutschen Bahn konzentriert. Die zugehörige Webanwendung ermöglicht es Benutzern, in Echtzeit zu erfahren, welche Züge
Das würde ich raus nehmen. Die Seite soll keine Echtzeitdaten darstellen und auch nicht dafür genutzt werden

2024-03-05 14:04 UTC, olech2412 commented on README.md
>  Dieses Projekt ist unter der [GNU General Public License](LICENSE) lizenziert - siehe die Datei LICENSE für weitere
Lizenz am besten gleich mit anpassen

2024-03-05 19:57 UTC, olech2412 commented on README.md
>  Dieses Projekt ist unter der [GNU General Public License](LICENSE) lizenziert - siehe die Datei LICENSE für weitere
Habe ich angepasst

2024-03-06 09:52 UTC, olech2412 approved these changes

2024-03-06 10:10 UTC, merged

2024-03-08 15:58 UTC, LenMPorath commented
BLOATED